//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldManageModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InInvoiceDetail
    {
        public int Id { get; set; }
        public string No { get; set; }
        public string Name { get; set; }
        public Nullable<double> WeightO { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<int> ItemType { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> InInvoiceId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual InInvoice InInvoice { get; set; }
    }
}
