//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldManageModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GoldManageEntities : DbContext
    {
        public GoldManageEntities()
            : base("name=GoldManageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<ExInvoice> ExInvoice { get; set; }
        public virtual DbSet<ExInvoiceDetail> ExInvoiceDetail { get; set; }
        public virtual DbSet<InInvoice> InInvoice { get; set; }
        public virtual DbSet<InInvoiceDetail> InInvoiceDetail { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<Store> Store { get; set; }
        public virtual DbSet<SubItem> SubItem { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
    }
}
