//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldManageModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsUse { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
